var epi_scores = {
  "Afghanistan": "0",
  "Albania": "5",
  "Algeria": "22",
  "American Samoa": "NA",
  "Andorra": "0",
  "Angola": "3",
  "Anguilla": "NA",
  "Antigua and Barbuda": "21",
  "Argentina": "23",
  "Armenia": "21",
  "Aruba": "NA",
  "Australia": "19",
  "Austria": "23",
  "Azerbaijan": "6",
  "Bahamas": "3",
  "Bahrain": "3",
  "Bangladesh": "21",
  "Barbados": "21",
  "Belarus": "9",
  "Belgium": "23",
  "Belize": "21",
  "Benin": "17",
  "Bermuda": "NA",
  "Bhutan": "0",
  "Bolivia": "7",
  "Bosnia and Herzegovina": "3",
  "Botswana": "5",
  "Brazil": "22",
  "British Virgin Islands": "NA",
  "Brunei Darussalam": "17",
  "Bulgaria": "23",
  "Burkina Faso": "19",
  "Burundi": "19",
  "Cambodia": "7",
  "Cameroon": "23",
  "Canada": "24",
  "Cape Verde": "21",
  "Cayman Islands": "NA",
  "Central African Republic": "20",
  "Chad": "18",
  "Chile": "23",
  "China": "13",
  "Colombia": "23",
  "Comoros": "4",
  "Congo": "23",
  "Cook Islands": "4",
  "Costa Rica": "20",
  "Cote d'Ivoire": "15",
  "Croatia": "24",
  "Cuba": "21",
  "Cyprus": "22",
  "Czech Republic": "24",
  "Dem. Rep. Congo": "4",
  "Denmark": "23",
  "Djibouti": "21",
  "Dominica": "3",
  "Dominican Republic": "24",
  "Ecuador": "23",
  "Egypt": "22",
  "El Salvador": "17",
  "Equatorial Guinea": "0",
  "Eritrea": "21",
  "Estonia": "24",
  "Ethiopia": "5",
  "Faeroe Islands": "NA",
  "Falkland Islands": "NA",
  "Fiji": "22",
  "Finland": "24",
  "France": "23",
  "French Guiana": "NA",
  "French Polynesia": "NA",
  "Gabon": "3",
  "Gambia": "21",
  "Georgia": "3",
  "Germany": "23",
  "Ghana": "21",
  "Gibraltar": "NA",
  "Greece": "21",
  "Greenland": "NA",
  "Grenada": "0",
  "Guadeloupe": "NA",
  "Guam": "NA",
  "Guatemala": "22",
  "Guinea": "22",
  "Guinea-Bissau": "3",
  "Guyana": "21",
  "Haiti": "1",
  "Holy See": "0",
  "Honduras": "21",
  "Hong Kong": "NA",
  "Hungary": "23",
  "Iceland": "24",
  "India": "23",
  "Indonesia": "21",
  "Iran": "21",
  "Iraq": "0",
  "Ireland": "24",
  "Isle of Man": "NA",
  "Israel": "1",
  "Italy": "20",
  "Jamaica": "23",
  "Japan": "23",
  "Jordan": "21",
  "Kazakhstan": "13",
  "Kenya": "21",
  "Kiribati": "3",
  "Kuwait": "23",
  "Kyrgyzstan": "22",
  "Laos": "15",
  "Latvia": "23",
  "Lebanon": "20",
  "Lesotho": "3",
  "Liberia": "23",
  "Libya": "3",
  "Liechtenstein": "21",
  "Lithuania": "24",
  "Luxembourg": "23",
  "Macao": "NA",
  "Macedonia": "22",
  "Madagascar": "21",
  "Malawi": "19",
  "Malaysia": "20",
  "Maldives": "3",
  "Mali": "4",
  "Malta": "1",
  "Marshall Islands": "3",
  "Martinique": "NA",
  "Mauritania": "3",
  "Mauritius": "23",
  "Mayotte": "NA",
  "Mexico": "20",
  "Micronesia": "3",
  "Moldova": "12",
  "Monaco": "23",
  "Mongolia": "19",
  "Montenegro": "18",
  "Montserrat": "NA",
  "Morocco": "21",
  "Mozambique": "21",
  "Myanmar": "15",
  "Namibia": "3",
  "Nauru": "3",
  "Nepal": "21",
  "Netherlands": "24",
  "Netherlands Antilles": "0",
  "New Caledonia": "NA",
  "New Zealand": "24",
  "Nicaragua": "19",
  "Niger": "14",
  "Nigeria": "21",
  "Niue": "3",
  "Norfolk Island": "NA",
  "North Korea": "3",
  "Northern Mariana Islands": "NA",
  "Norway": "23",
  "Oman": "6",
  "Pakistan": "12",
  "Palau": "3",
  "Panama": "24",
  "Papua New Guinea": "3",
  "Paraguay": "21",
  "Peru": "21",
  "Philippines": "18",
  "Pitcairn": "NA",
  "Poland": "24",
  "Portugal": "23",
  "Puerto Rico": "NA",
  "Qatar": "22",
  "Reunion": "NA",
  "Romania": "23",
  "Russia": "3",
  "Rwanda": "5",
  "Saint Helena": "NA",
  "Saint Kitts and Nevis": "21",
  "Saint Lucia": "5",
  "Saint Pierre and Miquelon": "NA",
  "Saint Vincent and the Grenadines": "3",
  "Samoa": "13",
  "San Marino": "0",
  "Sao Tome and Principe": "3",
  "Saudi Arabia": "23",
  "Senegal": "3",
  "Serbia": "23",
  "Seychelles": "12",
  "Sierra Leone": "3",
  "Singapore": "24",
  "Slovakia": "22",
  "Slovenia": "23",
  "Solomon Islands": "3",
  "Somalia": "3",
  "South Africa": "22",
  "South Korea": "23",
  "Spain": "23",
  "Sri Lanka": "21",
  "State of Palestine": "0",
  "Sudan": "21",
  "Suriname": "20",
  "Svalbard and Jan Mayen Islands": "NA",
  "Swaziland": "4",
  "Sweden": "23",
  "Switzerland": "23",
  "Syria": "21",
  "Taiwan": "18",
  "Tajikistan": "13",
  "Tanzania": "22",
  "Thailand": "23",
  "Timor-Leste": "0",
  "Togo": "21",
  "Tokelau": "0",
  "Tonga": "3",
  "Trinidad and Tobago": "24",
  "Tunisia": "19",
  "Turkey": "24",
  "Turkmenistan": "0",
  "Turks and Caicos Islands": "NA",
  "Tuvalu": "12",
  "Uganda": "4",
  "Ukraine": "17",
  "United Arab Emirates": "23",
  "United Kingdom": "24",
  "United States of America": "20",
  "United States Virgin Islands": "NA",
  "Uruguay": "21",
  "Uzbekistan": "0",
  "Vanuatu": "3",
  "Venezuela": "22",
  "Viet Nam": "22",
  "Wallis and Futuna Islands": "NA",
  "Western Sahara": "NA",
  "Yemen": "21",
  "Zambia": "18",
  "Zimbabwe": "3"
};